### ISSUE TITLE
english translations

### ISSUE THREAD

**Issue by r618** [IndieVisualLab/UnityGraphicsProgrammingSeries#1]
These look indeed brilliant !
I'm assuming there's no way of having English translations for them currently ?

**Comment by mattatz** [comment]
@r618 
Thank you for a request.
We already have a lot of requests for English translations, but have no time & motivation for it.

We have shared all document resources in our repositories.
(IndieVisualLab/UnityGraphicsProgrammingBook1 etc.)
So if you have a interest & motivation, please translate them into English!

**Comment by r618** [comment]
Hi no worries, thanks for reply
If only I could speak a word of Japanese (or Korean for that matter) -)
I'll at least spread the link around, maybe someone will make it happen
